### PR TITLE
Backend agnostic and no more imports hack

### LINKED ISSUE #8: Remove the Functions imports hack in tensor.py

### LINKED ISSUE #9: Make ops computation agnostic!
So that we can add multiple backend.

### PR DESCRIPTION
**Pull request by hbhungg**
Attempting to solve #9 and #8

### CODE REVIEW

**Comment by hbhungg** [comment]
How can we switch between device?

**Comment by hbhungg** [comment]
Also, using match case, which is python3.10 stuff, should we?

**Comment by AmitPress** [comment]
@hbhungg what about keeping an enum for Device to map different device accordingly. 

```python
class _Device:
  def __init__(self) -> None: # each string is buffer 
    self._buffers: List[str]  = [x.stem[len("ops_"):].upper() for x in (pathlib.Path(__file__).parent/"runtime").iterdir() if x.stem.startswith("ops_")]
    self.DEFAULT: str = functools.reduce(lambda val, ele: ele if getenv(ele) == 1 else val, self._buffers, None) or self._default_device()
  def canonicalize(self, device:str) -> str: return (device.split(":", 1)[0].upper() + ((":"+device.split(":", 1)[1]) if ':' in device else '')).replace(":0", "")
  def __getitem__(self, x:str) -> Union[Interpreted, Compiled]: return self._get_device(x.split(":")[0].upper())
  @functools.lru_cache(maxsize=None)  # this class is a singleton, pylint: disable=method-cache-max-size-none
  def _get_device(self, x:str) -> Union[Interpreted, Compiled]: return [cls for cname, cls in inspect.getmembers(importlib.import_module(f'tinygrad.runtime.ops_{x.lower()}')) if (cname.lower() == x.lower() + "buffer") and x in self._buffers][0]
  def _default_device(self) -> str:
    for device in ["METAL", "CUDA", "GPU"]:
      try:
        if self[device]: return device
      except Exception: pass
    return "CPU"
Device = _Device()
```

basically they have made a fancy class with some checks and standardized the output as you have seen... We will do the same with enum and will have some checks implemented on it.

**Comment by AmitPress** [comment]
@hbhungg like this 
```python
from enum import Enum

class Device(Enum):
    METAL = "METAL"
    CUDA = "CUDA"
    GPU = "GPU"
    CPU = "CUDA"

def get_device(device_name):
    device_name = device_name.upper().strip()
    for d in Device:
        if d.value == device_name:
            return d
    return Device.CUDA

print(get_device("gPu"))
```

**Pull request closed without merging**
